fix pannel typo for wilp*
system76/firmware-desktop pull request #8
Opened 2018-02-06 04:32 UTC by ahoneybun

2018-02-06 16:39 UTC, brs17 requested changes
Want to make that PR for all of the models? (because I'm pretty sure that typo is in all of them)

2018-02-07 01:32 UTC, ahoneybun commented
changes are done. please merge if it LGTM.

2018-02-07 15:43 UTC, brs17 commented
I think the sabl6 has the same typo as well

2018-02-07 17:14 UTC, brs17 approved these changes

2018-02-07 17:15 UTC, merged